baseURL = "https://xbytemx.github.io/"
languageCode = "en-us"
title = "xbytemx blog"

theme = "steam"
disqusShortname = "xbytemx"
googleAnalytics = ""
paginate = 10

[params]
	title = "xbytemx blog"
	subtitle = "Un lugar más donde dejar anecdotas"
	copyright = "Released under the MIT license."

	themecolor = "blue"

	favicon   = "favicon.ico"
	customCSS = []
	customJS  = []

	name = "Tony Palma"
	bio = "Yo solo toque la computadora y solita se apago"
	description = "La idea de este blog es documentar un poco mas sobre lo que aprendo"
	
	location = ""
	twitter = "xbytemx"
	linkedin = ""
	googleplus = ""
	facebook = ""
	instagram = ""
	github = "xbytemx"
	gitlab = ""
	bitbucket = ""

	keepReadingStr = "Keep reading"
	backtotopStr = "Back to top"
	shareStr = "Share"
	pageNotFoundTitle = "404 - Page not found"

