baseURL = "https://www.xbyte.mx"
languageCode = "en-us"
defaultContentLanguage = "en"
title = "xbytemx"
theme = "hello-friend-ng"

rssLimit = 10
enableEmoji = true
disqusShortname = "xbytemx"

[author]
  name = "Tony Palma"

[taxonomies]
  category = "blog"
  tag = "tags"
  series = "series"

[params]
  name = "Tony Palma"
  bio = "Yo solo toque la computadora y solita se apago"
  description = "Un blog donde escribo sobre pentesting, reversing, networking y CTFs"
  images = [""]
  keywords = "security, reversing, cloudsec, ctf, hackthebox, htb"

  dateform        = "Jan 2, 2006"
  dateformShort   = "Jan 2"
  dateformNum     = "2006-01-02"
  dateformNumTime = "2006-01-02 15:04 -0700"

  homeSubtitle = "Un lugar más donde dejar anecdotas"
  copyright = ' &#183; <a href="https://creativecommons.org/licenses/by-nc/4.0/" target="_blank" rel="noopener">CC BY-NC 4.0</a>'
  
  [[params.social]]
    name = "twitter"
    url = "https://twitter.com/xbytemx"

  [[params.social]]
    name = "instagram"
    url = "https://instagram.com/xbyte.mx"

  [[params.social]]
    name = "github"
    url = "https://github.com/xbytemx"

[menu]
  [[menu.main]]
    identifier = "blog"
    name = "Posts"
    url = "posts/"
    weight = 10

  [[menu.main]]
    name = "About"
    url = "about/"
    weight = 20
